# Generated by Django 5.2.15 on 2026-06-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client_created_at', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField(blank=True)),
                ('host', models.CharField(blank=True, max_length=32)),
                ('schema_version', models.IntegerField(default=0)),
                ('agent', models.JSONField(blank=True, default=dict)),
                ('environment', models.JSONField(blank=True, default=dict)),
                ('redaction', models.JSONField(blank=True, default=dict)),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('transcript_raw', models.JSONField(blank=True, default=list)),
                ('size_bytes', models.IntegerField(default=0)),
                ('remote_addr', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
